<?php

/**
 * @file
 * Contains winsports_complements.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function winsports_complements_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the winsports_complements module.
    case 'help.page.winsports_complements':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module allow render players in the display suite presentation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function winsports_complements_theme() {
  $config = \Drupal::config('winsports_complements.playersconfig')->get('players_plugins');
  
  $theme = [
    'winsports_complements' => [
      'render element' => 'children',
    ],
  ];
  
  foreach( $config as $key => $player){
    $theme[$player['id']] = [
      'render element' => 'children',
      'template' => 'player-'.str_replace('_','-',$player['id']),
      'variables' => [ 'player' => NULL ]
    ];
  }

  
  return $theme;
}
