<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

function custom_playlist_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.custom_playlist') {
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Playlist selected by default.') . '</p>';
    return $output;
  }
}

function custom_playlist_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id){
   switch ($form['#id']) {
    case 'views-exposed-form-videos-block-1':
      if(empty($_GET)){
        $filter_value = \Drupal::config('custom_playlist.settings')->get('filter_liga');
        dpm($filter_value);
        if($filter_value !== 'All'){
          $form_state->setUserInput(['field_tournament_round_target_id' => $filter_value]);
        }
      }
      break;
    case 'views-exposed-form-videos-block-4':
      if(empty($_GET)){
        $filter_value = \Drupal::config('custom_playlist.settings')->get('filter_torneo');
        dpm($filter_value);
        if($filter_value !== 'All'){
          $form_state->setUserInput(['field_tournament_round_target_id' => $filter_value]);
        }
      }
      break;
    case 'views-exposed-form-videos-block-5':
      if(empty($_GET)){
        $filter_value = \Drupal::config('custom_playlist.settings')->get('filter_copa');
        dpm($filter_value);
        if($filter_value !== 'All'){
          $form_state->setUserInput(['field_tournament_round_target_id' => $filter_value]);
        }
      }
      break;
    case 'views-exposed-form-videos-block-9':
      if(empty($_GET)){
        $filter_value = \Drupal::config('custom_playlist.settings')->get('filter_otros');
        dpm($filter_value);
        if($filter_value !== 'All'){
          $form_state->setUserInput(['field_category_target_id_1' => $filter_value]);
        }
      }
      break;
  }
}
