<?php

/**
 * @file
 * Contains winsports_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function winsports_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the winsports_migrate module.
    case 'help.page.winsports_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module migrate information the nodes and taxonomies from winsports (drupal 7)') . '</p>';
      return $output;

    default: 
  }
}
 
/**
 * Implements hook_theme().
 */
function winsports_migrate_theme() {
  return [
    'winsports_migrate' => [
      'render element' => 'children',
    ],
  ];
}
