<?php

/**
 * @file
 * Contains winsports.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function winsports_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the winsports module.
    case 'help.page.winsports':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module allow render players in the display suite presentation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function winsports_theme() {
  return [
    'winsports' => [
      'render element' => 'children',
    ],
  ];
}
